# Generated by Django 3.0.4 on 2020-04-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200415_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Description of the item'),
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='default.jpeg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='default.jpeg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='default.jpeg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default='default.jpeg', upload_to='product_pics'),
        ),
    ]
