# Generated by Django 3.0.4 on 2020-04-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200423_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
