# Generated by Django 3.0.4 on 2020-04-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='product'),
            preserve_default=False,
        ),
    ]
