# Generated by Django 3.0.4 on 2020-04-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
