# Generated by Django 3.0.4 on 2020-04-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='author',
            new_name='user',
        ),
    ]
