# Generated by Django 3.0.4 on 2020-05-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='BillingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.BillingAddress'),
        ),
    ]
