# Generated by Django 3.0.4 on 2020-05-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='home_address',
            field=models.CharField(default='121 Lubowa', max_length=100),
        ),
    ]
