# Generated by Django 3.0.4 on 2020-05-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200505_0537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
