# Generated by Django 3.0.4 on 2020-05-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200527_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cat',
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpeg', upload_to='product_pics')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
        ),
    ]
