# Generated by Django 3.0.4 on 2020-05-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='shop_profile'),
        ),
    ]
